# Generated by Django 4.1.3 on 2022-11-30 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nA', models.IntegerField(default=6)),
                ('epsilon', models.FloatField(default=1)),
                ('gamma', models.FloatField(default=0.9)),
                ('alpha', models.FloatField(default=0.2)),
                ('episode', models.IntegerField(default=0)),
            ],
        ),
    ]
