# Generated by Django 4.1.3 on 2022-12-01 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deepL_Taxi_App', '0002_agent_q'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='Q',
            field=models.JSONField(default=dict),
        ),
    ]
